// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.28.3
// source: google-billing-console/apps/user/pb/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 为了防止越权, 用户可以调整的权限范围只有10已下的权限
type TYPE int32

const (
	// 子账号, 无用户中心后台管理权限
	TYPE_SUB TYPE = 0
	// 主账号, 具有本域的所有权限
	TYPE_PRIMARY TYPE = 10
	// 超级管理员, 系统管理员, 万能的人, 不受权限系统约束
	TYPE_SUPPER TYPE = 15
)

// Enum value maps for TYPE.
var (
	TYPE_name = map[int32]string{
		0:  "SUB",
		10: "PRIMARY",
		15: "SUPPER",
	}
	TYPE_value = map[string]int32{
		"SUB":     0,
		"PRIMARY": 10,
		"SUPPER":  15,
	}
)

func (x TYPE) Enum() *TYPE {
	p := new(TYPE)
	*p = x
	return p
}

func (x TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_google_billing_console_apps_user_pb_user_proto_enumTypes[0].Descriptor()
}

func (TYPE) Type() protoreflect.EnumType {
	return &file_google_billing_console_apps_user_pb_user_proto_enumTypes[0]
}

func (x TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE.Descriptor instead.
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{0}
}

type PROVIDER int32

const (
	PROVIDER_LOCAL       PROVIDER = 0
	PROVIDER_LDAP        PROVIDER = 1
	PROVIDER_FEISHU      PROVIDER = 2
	PROVIDER_DINGDING    PROVIDER = 3
	PROVIDER_WECHAT_WORK PROVIDER = 4
)

// Enum value maps for PROVIDER.
var (
	PROVIDER_name = map[int32]string{
		0: "LOCAL",
		1: "LDAP",
		2: "FEISHU",
		3: "DINGDING",
		4: "WECHAT_WORK",
	}
	PROVIDER_value = map[string]int32{
		"LOCAL":       0,
		"LDAP":        1,
		"FEISHU":      2,
		"DINGDING":    3,
		"WECHAT_WORK": 4,
	}
)

func (x PROVIDER) Enum() *PROVIDER {
	p := new(PROVIDER)
	*p = x
	return p
}

func (x PROVIDER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PROVIDER) Descriptor() protoreflect.EnumDescriptor {
	return file_google_billing_console_apps_user_pb_user_proto_enumTypes[1].Descriptor()
}

func (PROVIDER) Type() protoreflect.EnumType {
	return &file_google_billing_console_apps_user_pb_user_proto_enumTypes[1]
}

func (x PROVIDER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PROVIDER.Descriptor instead.
func (PROVIDER) EnumDescriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{1}
}

type CREATE_FROM int32

const (
	CREATE_FROM_PRIMARY_ACCOUNT CREATE_FROM = 0
	CREATE_FROM_SELF            CREATE_FROM = 1
)

// Enum value maps for CREATE_FROM.
var (
	CREATE_FROM_name = map[int32]string{
		0: "PRIMARY_ACCOUNT",
		1: "SELF",
	}
	CREATE_FROM_value = map[string]int32{
		"PRIMARY_ACCOUNT": 0,
		"SELF":            1,
	}
)

func (x CREATE_FROM) Enum() *CREATE_FROM {
	p := new(CREATE_FROM)
	*p = x
	return p
}

func (x CREATE_FROM) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CREATE_FROM) Descriptor() protoreflect.EnumDescriptor {
	return file_google_billing_console_apps_user_pb_user_proto_enumTypes[2].Descriptor()
}

func (CREATE_FROM) Type() protoreflect.EnumType {
	return &file_google_billing_console_apps_user_pb_user_proto_enumTypes[2]
}

func (x CREATE_FROM) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CREATE_FROM.Descriptor instead.
func (CREATE_FROM) EnumDescriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{2}
}

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_MALE    Gender = 1
	Gender_FEMALE  Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "UNKNOWN",
		1: "MALE",
		2: "FEMALE",
	}
	Gender_value = map[string]int32{
		"UNKNOWN": 0,
		"MALE":    1,
		"FEMALE":  2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_google_billing_console_apps_user_pb_user_proto_enumTypes[3].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_google_billing_console_apps_user_pb_user_proto_enumTypes[3]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{3}
}

// User 用户账号
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 对象Id
	// @gotags: bson:"id" json:"id" bigquery:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"id" bigquery:"id"`
	// 元信息
	// @gotags: bson:",inline" json:"meta" bigquery:"meta"
	Meta *Meta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta" bson:",inline" bigquery:"meta"`
	// 定义信息
	// @gotags: bson:",inline" json:"spec" bigquery:"spec"
	Spec *CreateUserRequest `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec" bson:",inline" bigquery:"spec"`
	// 密码相关信息
	// @gotags: bson:"password" json:"password" bigquery:"password"
	Password *Password `protobuf:"bytes,4,opt,name=password,proto3" json:"password" bson:"password" bigquery:"password"`
	// 用户状态
	// @gotags: bson:"status" json:"status" bigquery:"status"
	Status *Status `protobuf:"bytes,5,opt,name=status,proto3" json:"status" bson:"status" bigquery:"status"`
	// 飞书token
	// @gotags: bson:"feishu_token" json:"feishu_token" bigquery:"feishu_token"
	FeishuToken *FeishuAccessToken `protobuf:"bytes,6,opt,name=feishu_token,json=feishuToken,proto3" json:"feishu_token" bson:"feishu_token" bigquery:"feishu_token"`
	// 钉钉token
	// @gotags: bson:"dingding_token" json:"dingding_token" bigquery:"dingding_token"
	DingdingToken *DingDingAccessToken `protobuf:"bytes,7,opt,name=dingding_token,json=dingdingToken,proto3" json:"dingding_token" bson:"dingding_token" bigquery:"dingding_token"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *User) GetSpec() *CreateUserRequest {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *User) GetPassword() *Password {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *User) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *User) GetFeishuToken() *FeishuAccessToken {
	if x != nil {
		return x.FeishuToken
	}
	return nil
}

func (x *User) GetDingdingToken() *DingDingAccessToken {
	if x != nil {
		return x.DingdingToken
	}
	return nil
}

// -------------------------------------------------------------
// CreateUserRequest 创建用户请求
type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 账号提供方
	// @gotags: json:"provider" bson:"provider" bigquery:"provider"
	Provider PROVIDER `protobuf:"varint,1,opt,name=provider,proto3,enum=kade_chen.google_billing_console.user.PROVIDER" json:"provider" bson:"provider" bigquery:"provider"`
	// 用户类型
	// @gotags: json:"type" bson:"type" bigquery:"type"
	Type TYPE `protobuf:"varint,2,opt,name=type,proto3,enum=kade_chen.google_billing_console.user.TYPE" json:"type" bson:"type" bigquery:"type"`
	// 是否共享账号
	// @gotags: json:"shared" bson:"shared" bigquery:"shared"
	Shared bool `protobuf:"varint,15,opt,name=shared,proto3" json:"shared" bson:"shared" bigquery:"shared"`
	// 创建来源
	// @gotags: json:"create_from" bson:"create_from" bigquery:"create_from"
	CreateFrom CREATE_FROM `protobuf:"varint,3,opt,name=create_from,json=createFrom,proto3,enum=kade_chen.google_billing_console.user.CREATE_FROM" json:"create_from" bson:"create_from" bigquery:"create_from"`
	// 创建类型
	// @gotags: json:"create_by" bson:"create_by" bigquery:"create_by"
	CreateBy string `protobuf:"bytes,13,opt,name=create_by,json=createBy,proto3" json:"create_by" bson:"create_by" bigquery:"create_by"`
	// 域信息
	// @gotags: json:"domain" bson:"domain" validate:"required" bigquery:"domain"
	Domain string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain" bson:"domain" validate:"required" bigquery:"domain"`
	// 用户账号名称
	// @gotags: json:"username" bson:"username" validate:"required,lte=60" bigquery:"username"
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username" bson:"username" validate:"required,lte=60" bigquery:"username"`
	// 密码相关信息
	// @gotags: json:"password" bson:"-" validate:"required,lte=80" bigquery:"password"
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password" bson:"-" validate:"required,lte=80" bigquery:"password"`
	// 用户描述
	// @gotags: json:"description" bson:"description" bigquery:"description"
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description" bson:"description" bigquery:"description"`
	// 用户标签
	// @gotags: json:"labels" bson:"labels" bigquery:"labels"
	Labels map[string]string `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"labels" bigquery:"labels"`
	// 用户飞书相关信息
	// @gotags: json:"feishu" bson:"feishu" bigquery:"feishu"
	Feishu *Feishu `protobuf:"bytes,8,opt,name=feishu,proto3" json:"feishu" bson:"feishu" bigquery:"feishu"`
	// 用户钉钉相关信息
	// @gotags: json:"dingding" bson:"dingding" bigquery:"dingding"
	Dingding *DingDing `protobuf:"bytes,9,opt,name=dingding,proto3" json:"dingding" bson:"dingding" bigquery:"dingding"`
	// 用户企业微信相关信息
	// @gotags: json:"wechatwork" bson:"wechatwork" bigquery:"wechatwork"
	Wechatwork *WechatWork `protobuf:"bytes,10,opt,name=wechatwork,proto3" json:"wechatwork" bson:"wechatwork" bigquery:"wechatwork"`
	// 使用全名作为uid
	// @gotags: json:"use_full_named_uid" bson:"use_full_named_uid" bigquery:"use_full_named_uid"
	UseFullNamedUid bool `protobuf:"varint,12,opt,name=use_full_named_uid,json=useFullNamedUid,proto3" json:"use_full_named_uid" bson:"use_full_named_uid" bigquery:"use_full_named_uid"`
	// Profile信息
	// @gotags: bson:"profile" json:"profile" bigquery:"profile"
	Profile *Profile `protobuf:"bytes,14,opt,name=profile,proto3" json:"profile" bson:"profile" bigquery:"profile"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetProvider() PROVIDER {
	if x != nil {
		return x.Provider
	}
	return PROVIDER_LOCAL
}

func (x *CreateUserRequest) GetType() TYPE {
	if x != nil {
		return x.Type
	}
	return TYPE_SUB
}

func (x *CreateUserRequest) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *CreateUserRequest) GetCreateFrom() CREATE_FROM {
	if x != nil {
		return x.CreateFrom
	}
	return CREATE_FROM_PRIMARY_ACCOUNT
}

func (x *CreateUserRequest) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *CreateUserRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateUserRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateUserRequest) GetFeishu() *Feishu {
	if x != nil {
		return x.Feishu
	}
	return nil
}

func (x *CreateUserRequest) GetDingding() *DingDing {
	if x != nil {
		return x.Dingding
	}
	return nil
}

func (x *CreateUserRequest) GetWechatwork() *WechatWork {
	if x != nil {
		return x.Wechatwork
	}
	return nil
}

func (x *CreateUserRequest) GetUseFullNamedUid() bool {
	if x != nil {
		return x.UseFullNamedUid
	}
	return false
}

func (x *CreateUserRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type Feishu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否启用飞书认证
	// @gotags: bson:"enabled" json:"enabled" bigquery:"enabled"
	Enabled bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled" bson:"enabled" bigquery:"enabled"`
	// 用户在飞书应用内的唯一标识
	// @gotags: bson:"open_id" json:"open_id" bigquery:"open_id"
	OpenId string `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id" bson:"open_id" bigquery:"open_id"`
	// 用户统一ID
	// @gotags: bson:"union_id" json:"union_id" bigquery:"union_id"
	UnionId string `protobuf:"bytes,2,opt,name=union_id,json=unionId,proto3" json:"union_id" bson:"union_id" bigquery:"union_id"`
	// 用户 user id
	// @gotags: bson:"user_id" json:"user_id" bigquery:"user_id"
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id" bson:"user_id" bigquery:"user_id"`
}

func (x *Feishu) Reset() {
	*x = Feishu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Feishu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feishu) ProtoMessage() {}

func (x *Feishu) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feishu.ProtoReflect.Descriptor instead.
func (*Feishu) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *Feishu) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Feishu) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *Feishu) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *Feishu) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DingDing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否启用钉钉认证
	// @gotags: bson:"enabled" json:"enabled" bigquery:"enabled"
	Enabled bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled" bson:"enabled" bigquery:"enabled"`
	// 用户在飞书应用内的唯一标识
	// @gotags: bson:"open_id" json:"open_id" bigquery:"open_id"
	OpenId string `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id" bson:"open_id" bigquery:"open_id"`
	// 用户统一ID
	// @gotags: bson:"union_id" json:"union_id" bigquery:"union_id"
	UnionId string `protobuf:"bytes,2,opt,name=union_id,json=unionId,proto3" json:"union_id" bson:"union_id" bigquery:"union_id"`
}

func (x *DingDing) Reset() {
	*x = DingDing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DingDing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DingDing) ProtoMessage() {}

func (x *DingDing) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DingDing.ProtoReflect.Descriptor instead.
func (*DingDing) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *DingDing) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DingDing) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *DingDing) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

type WechatWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否启用企业微信认证
	// @gotags: bson:"enabled" json:"enabled" bigquery:"enabled"
	Enabled bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled" bson:"enabled" bigquery:"enabled"`
	// 用户在企业微信中的Id
	// @gotags: bson:"user_id" json:"user_id" bigquery:"user_id"
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id" bson:"user_id" bigquery:"user_id"`
	// 用户在企业微信唯一标识
	// @gotags: bson:"open_id" json:"open_id" bigquery:"open_id"
	OpenId string `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id" bson:"open_id" bigquery:"open_id"`
}

func (x *WechatWork) Reset() {
	*x = WechatWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatWork) ProtoMessage() {}

func (x *WechatWork) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatWork.ProtoReflect.Descriptor instead.
func (*WechatWork) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{4}
}

func (x *WechatWork) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WechatWork) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WechatWork) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户真实姓名
	// @gotags: bson:"real_name" json:"real_name" validate:"lte=10" bigquery:"real_name"
	RealName string `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name" bson:"real_name" validate:"lte=10" bigquery:"real_name"`
	// 用户昵称
	// @gotags: bson:"nick_name" json:"nick_name" validate:"lte=30" bigquery:"nick_name"
	NickName string `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name" bson:"nick_name" validate:"lte=30" bigquery:"nick_name"`
	// 手机号码
	// @gotags: bson:"phone" json:"phone" validate:"lte=30" bigquery:"phone"
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone" bson:"phone" validate:"lte=30" bigquery:"phone"`
	// 邮箱
	// @gotags: bson:"email" json:"email" validate:"lte=30" bigquery:"email"
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email" bson:"email" validate:"lte=30" bigquery:"email"`
	// 用户住址
	// @gotags: bson:"address" json:"address" validate:"lte=120" bigquery:"address"
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address" bson:"address" validate:"lte=120" bigquery:"address"`
	// 性别
	// @gotags: bson:"gender" json:"gender" validate:"lte=10" bigquery:"gender"
	Gender Gender `protobuf:"varint,6,opt,name=gender,proto3,enum=kade_chen.google_billing_console.user.Gender" json:"gender" bson:"gender" validate:"lte=10" bigquery:"gender"`
	// 头像
	// @gotags: bson:"avatar" json:"avatar" validate:"lte=300" bigquery:"avatar"
	Avatar string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar" bson:"avatar" validate:"lte=300" bigquery:"avatar"`
	// 用户使用的语言
	// @gotags: bson:"language" json:"language" validate:"lte=40" bigquery:"language"
	Language string `protobuf:"bytes,8,opt,name=language,proto3" json:"language" bson:"language" validate:"lte=40" bigquery:"language"`
	// 用户所在的城市
	// @gotags: bson:"city" json:"city" validate:"lte=40" bigquery:"city"
	City string `protobuf:"bytes,9,opt,name=city,proto3" json:"city" bson:"city" validate:"lte=40" bigquery:"city"`
	// 用户所在的省
	// @gotags: bson:"province" json:"province" validate:"lte=40" bigquery:"province"
	Province string `protobuf:"bytes,10,opt,name=province,proto3" json:"province" bson:"province" validate:"lte=40" bigquery:"province"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{5}
}

func (x *Profile) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *Profile) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Profile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Profile) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_UNKNOWN
}

func (x *Profile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Profile) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Profile) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Profile) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

type Password struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hash过后的密码
	// @gotags: bson:"password" json:"password,omitempty" bigquery:"password"
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty" bson:"password" bigquery:"password"`
	// 密码创建时间
	// @gotags: bson:"create_at" json:"create_at" bigquery:"create_at"
	CreateAt int64 `protobuf:"varint,2,opt,name=create_at,json=createAt,proto3" json:"create_at" bson:"create_at" bigquery:"create_at"`
	// 密码更新时间
	// @gotags: bson:"update_at" json:"update_at" bigquery:"update_at"
	UpdateAt int64 `protobuf:"varint,3,opt,name=update_at,json=updateAt,proto3" json:"update_at" bson:"update_at" bigquery:"update_at"`
	// 密码需要被重置
	// @gotags: bson:"need_reset" json:"need_reset" bigquery:"need_reset"
	NeedReset bool `protobuf:"varint,4,opt,name=need_reset,json=needReset,proto3" json:"need_reset" bson:"need_reset" bigquery:"need_reset"`
	// 需要重置的原因
	// @gotags: bson:"reset_reason" json:"reset_reason" bigquery:"reset_reason"
	ResetReason string `protobuf:"bytes,5,opt,name=reset_reason,json=resetReason,proto3" json:"reset_reason" bson:"reset_reason" bigquery:"reset_reason"`
	// 密码过期时间
	// @gotags: bson:"expired_days" json:"expired_days" bigquery:"expired_days"
	ExpiredDays uint32 `protobuf:"varint,6,opt,name=expired_days,json=expiredDays,proto3" json:"expired_days" bson:"expired_days" bigquery:"expired_days"`
	// 密码过期前多少天开始提醒
	// @gotags: bson:"expired_remind" json:"expired_remind" bigquery:"expired_remind"
	ExpiredRemind uint32 `protobuf:"varint,7,opt,name=expired_remind,json=expiredRemind,proto3" json:"expired_remind" bson:"expired_remind" bigquery:"expired_remind"`
	// 历史密码
	// @gotags: bson:"history" json:"history,omitempty" bigquery:"history"
	History []string `protobuf:"bytes,8,rep,name=history,proto3" json:"history,omitempty" bson:"history" bigquery:"history"`
}

func (x *Password) Reset() {
	*x = Password{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{6}
}

func (x *Password) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Password) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Password) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *Password) GetNeedReset() bool {
	if x != nil {
		return x.NeedReset
	}
	return false
}

func (x *Password) GetResetReason() string {
	if x != nil {
		return x.ResetReason
	}
	return ""
}

func (x *Password) GetExpiredDays() uint32 {
	if x != nil {
		return x.ExpiredDays
	}
	return 0
}

func (x *Password) GetExpiredRemind() uint32 {
	if x != nil {
		return x.ExpiredRemind
	}
	return 0
}

func (x *Password) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户是否初始化
	// @gotags: bson:"is_initialized" json:"is_initialized" bigquery:"is_initialized"
	IsInitialized bool `protobuf:"varint,5,opt,name=is_initialized,json=isInitialized,proto3" json:"is_initialized" bson:"is_initialized" bigquery:"is_initialized"`
	// 是否冻结
	// @gotags: bson:"locked" json:"locked" bigquery:"locked"
	Locked bool `protobuf:"varint,1,opt,name=locked,proto3" json:"locked" bson:"locked" bigquery:"locked"`
	// 冻结时间
	// @gotags: bson:"locked_time" json:"locked_time" bigquery:"locked_time"
	LockedTime int64 `protobuf:"varint,2,opt,name=locked_time,json=lockedTime,proto3" json:"locked_time" bson:"locked_time" bigquery:"locked_time"`
	// 冻结原因
	// @gotags: bson:"locked_reson" json:"locked_reson" bigquery:"locked_reson"
	LockedReson string `protobuf:"bytes,3,opt,name=locked_reson,json=lockedReson,proto3" json:"locked_reson" bson:"locked_reson" bigquery:"locked_reson"`
	// 解冻时间
	// @gotags: bson:"unlock_time" json:"unlock_time" bigquery:"unlock_time"
	UnlockTime int64 `protobuf:"varint,4,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time" bson:"unlock_time" bigquery:"unlock_time"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{7}
}

func (x *Status) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

func (x *Status) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *Status) GetLockedTime() int64 {
	if x != nil {
		return x.LockedTime
	}
	return 0
}

func (x *Status) GetLockedReson() string {
	if x != nil {
		return x.LockedReson
	}
	return ""
}

func (x *Status) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

type FeishuAccessToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 飞书服务器授权的access_token
	// @gotags: bson:"access_token" json:"access_token" bigquery:"access_token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token" bson:"access_token" bigquery:"access_token"`
	// token类型
	// @gotags: bson:"token_type" json:"token_type" bigquery:"token_type"
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type" bson:"token_type" bigquery:"token_type"`
	// access_token 颁发时间
	// @gotags: bson:"issue_at" json:"issue_at" bigquery:"issue_at"
	IssueAt int64 `protobuf:"varint,3,opt,name=issue_at,json=issueAt,proto3" json:"issue_at" bson:"issue_at" bigquery:"issue_at"`
	// access_token 的有效期
	// @gotags: bson:"expires_in" json:"expires_in" bigquery:"expires_in"
	ExpiresIn int64 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in" bson:"expires_in" bigquery:"expires_in"`
	// refresh_token
	// @gotags: bson:"refresh_token" json:"refresh_token" bigquery:"refresh_token"
	RefreshToken string `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token" bson:"refresh_token" bigquery:"refresh_token"`
	// refresh_token 的有效期
	// @gotags: bson:"refresh_expires_in" json:"refresh_expires_in" bigquery:"refresh_expires_in"
	RefreshExpiresIn int64 `protobuf:"varint,6,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in" bson:"refresh_expires_in" bigquery:"refresh_expires_in"`
}

func (x *FeishuAccessToken) Reset() {
	*x = FeishuAccessToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeishuAccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeishuAccessToken) ProtoMessage() {}

func (x *FeishuAccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeishuAccessToken.ProtoReflect.Descriptor instead.
func (*FeishuAccessToken) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{8}
}

func (x *FeishuAccessToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *FeishuAccessToken) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *FeishuAccessToken) GetIssueAt() int64 {
	if x != nil {
		return x.IssueAt
	}
	return 0
}

func (x *FeishuAccessToken) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *FeishuAccessToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *FeishuAccessToken) GetRefreshExpiresIn() int64 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

type DingDingAccessToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 生成的accessToken
	// @gotags: bson:"access_token" json:"accessToken" bigquery:"access_token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"accessToken" bson:"access_token" bigquery:"access_token"`
	// refresh_token
	// @gotags: bson:"refresh_token" json:"refreshToken" bigquery:"refresh_token"
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken" bson:"refresh_token" bigquery:"refresh_token"`
	// 超时时间
	// @gotags: bson:"expires_in" json:"expireIn" bigquery:"expires_in"
	ExpiresIn int64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expireIn" bson:"expires_in" bigquery:"expires_in"`
	// 所选企业corpId
	// @gotags: bson:"corp_id" json:"corpId" bigquery:"corp_id"
	CorpId string `protobuf:"bytes,4,opt,name=corp_id,json=corpId,proto3" json:"corpId" bson:"corp_id" bigquery:"corp_id"`
	// access_token 颁发时间
	// @gotags: bson:"issue_at" json:"issue_at" bigquery:"issue_at"
	IssueAt int64 `protobuf:"varint,5,opt,name=issue_at,json=issueAt,proto3" json:"issue_at" bson:"issue_at" bigquery:"issue_at"`
}

func (x *DingDingAccessToken) Reset() {
	*x = DingDingAccessToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DingDingAccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DingDingAccessToken) ProtoMessage() {}

func (x *DingDingAccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DingDingAccessToken.ProtoReflect.Descriptor instead.
func (*DingDingAccessToken) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{9}
}

func (x *DingDingAccessToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DingDingAccessToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *DingDingAccessToken) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *DingDingAccessToken) GetCorpId() string {
	if x != nil {
		return x.CorpId
	}
	return ""
}

func (x *DingDingAccessToken) GetIssueAt() int64 {
	if x != nil {
		return x.IssueAt
	}
	return 0
}

type UserSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 总数量
	// @gotags: bson:"total" json:"total" bigquery:"total"
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total" bson:"total" bigquery:"total"`
	// 数据项
	// @gotags: bson:"items" json:"items" bigquery:"items"
	Items []*User `protobuf:"bytes,2,rep,name=items,proto3" json:"items" bson:"items" bigquery:"items"`
}

func (x *UserSet) Reset() {
	*x = UserSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSet) ProtoMessage() {}

func (x *UserSet) ProtoReflect() protoreflect.Message {
	mi := &file_google_billing_console_apps_user_pb_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSet.ProtoReflect.Descriptor instead.
func (*UserSet) Descriptor() ([]byte, []int) {
	return file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserSet) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_google_billing_console_apps_user_pb_user_proto protoreflect.FileDescriptor

var file_google_billing_console_apps_user_pb_user_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2d, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x2d, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x25, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2d,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2d, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf9, 0x03, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x3f, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x12, 0x4c, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x38, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12,
	0x4b, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x45, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6b,
	0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x5b, 0x0a, 0x0c, 0x66, 0x65, 0x69, 0x73, 0x68, 0x75, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6b, 0x61, 0x64, 0x65,
	0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x46, 0x65, 0x69, 0x73, 0x68, 0x75, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x0b, 0x66, 0x65, 0x69, 0x73, 0x68, 0x75, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x61, 0x0a, 0x0e, 0x64, 0x69, 0x6e, 0x67, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f,
	0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x44, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x0d, 0x64, 0x69, 0x6e, 0x67, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x94, 0x07, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4b, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x6b, 0x61,
	0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x54, 0x59, 0x50,
	0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x12,
	0x53, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x62,
	0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x5c, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63,
	0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x45, 0x0a, 0x06, 0x66, 0x65, 0x69, 0x73, 0x68, 0x75, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x69, 0x73, 0x68, 0x75,
	0x52, 0x06, 0x66, 0x65, 0x69, 0x73, 0x68, 0x75, 0x12, 0x4b, 0x0a, 0x08, 0x64, 0x69, 0x6e, 0x67,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6b, 0x61, 0x64,
	0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x44, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x64, 0x69, 0x6e,
	0x67, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x51, 0x0a, 0x0a, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6b, 0x61, 0x64, 0x65,
	0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x0a, 0x77, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2b, 0x0a, 0x12, 0x75, 0x73, 0x65, 0x5f,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x64, 0x55, 0x69, 0x64, 0x12, 0x48, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68,
	0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x1a,
	0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6f, 0x0a, 0x06, 0x46, 0x65,
	0x69, 0x73, 0x68, 0x75, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x08, 0x44,
	0x69, 0x6e, 0x67, 0x44, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x0a, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x22,
	0xb4, 0x02, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x65, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x45, 0x0a, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x6b, 0x61,
	0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x22, 0x86, 0x02, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x65,
	0x64, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6e,
	0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x65,
	0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x44, 0x61, 0x79, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22,
	0xac, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x73,
	0x5f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xe2,
	0x01, 0x0a, 0x11, 0x46, 0x65, 0x69, 0x73, 0x68, 0x75, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x5f,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x73, 0x49, 0x6e, 0x22, 0xb0, 0x01, 0x0a, 0x13, 0x44, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x6e, 0x67,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x49, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x72, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x41, 0x74, 0x22, 0x62, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x41, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x61, 0x64, 0x65, 0x5f, 0x63, 0x68,
	0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0x28, 0x0a, 0x04, 0x54, 0x59,
	0x50, 0x45, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x52, 0x49, 0x4d, 0x41, 0x52, 0x59, 0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x50, 0x50,
	0x45, 0x52, 0x10, 0x0f, 0x2a, 0x4a, 0x0a, 0x08, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52,
	0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x44, 0x41, 0x50, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x49, 0x53, 0x48, 0x55, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x4e, 0x47, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12,
	0x0f, 0x0a, 0x0b, 0x57, 0x45, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x04,
	0x2a, 0x2c, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x12,
	0x13, 0x0a, 0x0f, 0x50, 0x52, 0x49, 0x4d, 0x41, 0x52, 0x59, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x46, 0x10, 0x01, 0x2a, 0x2b,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x37, 0x5a, 0x35, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x64, 0x65, 0x2d, 0x63,
	0x68, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2d, 0x62, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x2d, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_billing_console_apps_user_pb_user_proto_rawDescOnce sync.Once
	file_google_billing_console_apps_user_pb_user_proto_rawDescData = file_google_billing_console_apps_user_pb_user_proto_rawDesc
)

func file_google_billing_console_apps_user_pb_user_proto_rawDescGZIP() []byte {
	file_google_billing_console_apps_user_pb_user_proto_rawDescOnce.Do(func() {
		file_google_billing_console_apps_user_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_billing_console_apps_user_pb_user_proto_rawDescData)
	})
	return file_google_billing_console_apps_user_pb_user_proto_rawDescData
}

var file_google_billing_console_apps_user_pb_user_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_google_billing_console_apps_user_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_google_billing_console_apps_user_pb_user_proto_goTypes = []interface{}{
	(TYPE)(0),                   // 0: kade_chen.google_billing_console.user.TYPE
	(PROVIDER)(0),               // 1: kade_chen.google_billing_console.user.PROVIDER
	(CREATE_FROM)(0),            // 2: kade_chen.google_billing_console.user.CREATE_FROM
	(Gender)(0),                 // 3: kade_chen.google_billing_console.user.Gender
	(*User)(nil),                // 4: kade_chen.google_billing_console.user.User
	(*CreateUserRequest)(nil),   // 5: kade_chen.google_billing_console.user.CreateUserRequest
	(*Feishu)(nil),              // 6: kade_chen.google_billing_console.user.Feishu
	(*DingDing)(nil),            // 7: kade_chen.google_billing_console.user.DingDing
	(*WechatWork)(nil),          // 8: kade_chen.google_billing_console.user.WechatWork
	(*Profile)(nil),             // 9: kade_chen.google_billing_console.user.Profile
	(*Password)(nil),            // 10: kade_chen.google_billing_console.user.Password
	(*Status)(nil),              // 11: kade_chen.google_billing_console.user.Status
	(*FeishuAccessToken)(nil),   // 12: kade_chen.google_billing_console.user.FeishuAccessToken
	(*DingDingAccessToken)(nil), // 13: kade_chen.google_billing_console.user.DingDingAccessToken
	(*UserSet)(nil),             // 14: kade_chen.google_billing_console.user.UserSet
	nil,                         // 15: kade_chen.google_billing_console.user.CreateUserRequest.LabelsEntry
	(*Meta)(nil),                // 16: kade_chen.google_billing_console.user.Meta
}
var file_google_billing_console_apps_user_pb_user_proto_depIdxs = []int32{
	16, // 0: kade_chen.google_billing_console.user.User.meta:type_name -> kade_chen.google_billing_console.user.Meta
	5,  // 1: kade_chen.google_billing_console.user.User.spec:type_name -> kade_chen.google_billing_console.user.CreateUserRequest
	10, // 2: kade_chen.google_billing_console.user.User.password:type_name -> kade_chen.google_billing_console.user.Password
	11, // 3: kade_chen.google_billing_console.user.User.status:type_name -> kade_chen.google_billing_console.user.Status
	12, // 4: kade_chen.google_billing_console.user.User.feishu_token:type_name -> kade_chen.google_billing_console.user.FeishuAccessToken
	13, // 5: kade_chen.google_billing_console.user.User.dingding_token:type_name -> kade_chen.google_billing_console.user.DingDingAccessToken
	1,  // 6: kade_chen.google_billing_console.user.CreateUserRequest.provider:type_name -> kade_chen.google_billing_console.user.PROVIDER
	0,  // 7: kade_chen.google_billing_console.user.CreateUserRequest.type:type_name -> kade_chen.google_billing_console.user.TYPE
	2,  // 8: kade_chen.google_billing_console.user.CreateUserRequest.create_from:type_name -> kade_chen.google_billing_console.user.CREATE_FROM
	15, // 9: kade_chen.google_billing_console.user.CreateUserRequest.labels:type_name -> kade_chen.google_billing_console.user.CreateUserRequest.LabelsEntry
	6,  // 10: kade_chen.google_billing_console.user.CreateUserRequest.feishu:type_name -> kade_chen.google_billing_console.user.Feishu
	7,  // 11: kade_chen.google_billing_console.user.CreateUserRequest.dingding:type_name -> kade_chen.google_billing_console.user.DingDing
	8,  // 12: kade_chen.google_billing_console.user.CreateUserRequest.wechatwork:type_name -> kade_chen.google_billing_console.user.WechatWork
	9,  // 13: kade_chen.google_billing_console.user.CreateUserRequest.profile:type_name -> kade_chen.google_billing_console.user.Profile
	3,  // 14: kade_chen.google_billing_console.user.Profile.gender:type_name -> kade_chen.google_billing_console.user.Gender
	4,  // 15: kade_chen.google_billing_console.user.UserSet.items:type_name -> kade_chen.google_billing_console.user.User
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_google_billing_console_apps_user_pb_user_proto_init() }
func file_google_billing_console_apps_user_pb_user_proto_init() {
	if File_google_billing_console_apps_user_pb_user_proto != nil {
		return
	}
	file_google_billing_console_apps_user_pb_meta_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Feishu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DingDing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Password); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeishuAccessToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DingDingAccessToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_billing_console_apps_user_pb_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_billing_console_apps_user_pb_user_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_billing_console_apps_user_pb_user_proto_goTypes,
		DependencyIndexes: file_google_billing_console_apps_user_pb_user_proto_depIdxs,
		EnumInfos:         file_google_billing_console_apps_user_pb_user_proto_enumTypes,
		MessageInfos:      file_google_billing_console_apps_user_pb_user_proto_msgTypes,
	}.Build()
	File_google_billing_console_apps_user_pb_user_proto = out.File
	file_google_billing_console_apps_user_pb_user_proto_rawDesc = nil
	file_google_billing_console_apps_user_pb_user_proto_goTypes = nil
	file_google_billing_console_apps_user_pb_user_proto_depIdxs = nil
}
